# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 20:11
from __future__ import unicode_literals

from django.db import migrations

def create_standard_groups(apps, schema_editor):
    """
    Removes Editors, renames Moderators to Operators
    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.get(name='Editors').delete()
    operators = Group.objects.get(name='Moderators')
    operators.name = 'Operators'
    operators.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length')
    ]

    operations = [
        migrations.RunPython(create_standard_groups),
    ]
