version: "2.1"
services:
  mysql:
    image: mysql:5.7
    container_name: designer.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "designer"
    networks:
      - devstack_default
    volumes:
      - designer_mysql:/var/lib/mysql
    # Uncomment these lines to access the database from localhost
    # ports:
    #  - "3307:3306"

  designer:
    image: edxops/designer:latest
    container_name: designer.app
    volumes:
      - .:/edx/app/designer
    command: bash -c 'while true; do python /edx/app/designer/manage.py runserver 0.0.0.0:18808; sleep 2; done'
    ports:
      - "18808:18808"
    depends_on:
      - mysql
    networks:
      - devstack_default
    # Allows attachment to this container using 'docker attach <containerID>'.
    stdin_open: true
    tty: true
    environment:
      DJANGO_SETTINGS_MODULE: designer.settings.devstack
      ENABLE_DJANGO_TOOLBAR: 1


networks:
  devstack_default:
    external: true

volumes:
  designer_mysql:
