# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 20:15
from __future__ import unicode_literals

import designer.apps.branding.models
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('pages', '0002_programpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_logo_alt_text', models.CharField(default='', max_length=256, verbose_name='Logo Alt Text')),
                ('banner_border_color', models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True, validators=[designer.apps.branding.models.validate_hexadecimal_color])),
            ],
        ),
        migrations.CreateModel(
            name='IndexPageBranding',
            fields=[
                ('branding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='branding.Branding')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_page_branding', to='pages.IndexPage', unique=True)),
            ],
            bases=('branding.branding',),
        ),
        migrations.CreateModel(
            name='ProgramPageBranding',
            fields=[
                ('branding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='branding.Branding')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_page_branding', to='pages.ProgramPage', unique=True)),
            ],
            bases=('branding.branding',),
        ),
        migrations.AddField(
            model_name='branding',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='branding',
            name='organization_logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo Image'),
        ),
        migrations.AddField(
            model_name='branding',
            name='texture_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Texture Image'),
        ),
    ]
