# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 15:12
from __future__ import unicode_literals
from wagtail.images.models import Image
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='organization_logo_alt_text',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Logo Alt Text'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='organization_logo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo Image'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='texture_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Texture Image'),
        ),
    ]
