# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_auto_20190703_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='texture_image',
        ),
    ]
