# Generated by Django 1.11.23 on 2019-10-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_auto_20190703_1512'),
        ('pages', '0017_copy_existing_program_branding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='texture_image',
        ),
    ]
