# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 19:32
from __future__ import unicode_literals

import designer.apps.sitebranding.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(max_length=128, verbose_name='Program Title')),
                ('organization_logo_alt_text', models.CharField(default='', max_length=256, verbose_name='Logo Alt Text')),
                ('banner_border_color', models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True, validators=[designer.apps.sitebranding.models.validate_hexadecimal_color])),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Cover Image')),
                ('organization_logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
                ('texture_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Texture Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
