# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
        ('pages', '0002_programpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageBranding',
            fields=[
                ('branding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='branding.Branding')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_page_branding', to='pages.IndexPage', unique=True)),
            ],
            bases=('branding.branding',),
        ),
        migrations.CreateModel(
            name='ProgramPageBranding',
            fields=[
                ('branding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='branding.Branding')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_page_branding', to='pages.ProgramPage', unique=True)),
            ],
            bases=('branding.branding',),
        ),
    ]
