# Generated by Django 1.11.21 on 2019-06-13 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_programpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
