# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 17:54
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_indexpagebranding_programpagebranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpagebranding',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='pages.IndexPage', unique=True),
        ),
        migrations.AlterField(
            model_name='programpagebranding',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='pages.ProgramPage', unique=True),
        ),
    ]
