# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190613_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
