# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190701_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
