# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190611_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
