# Generated by Django 1.11.21 on 2019-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190703_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='indexpagebranding',
            name='site_title',
        ),
        migrations.RemoveField(
            model_name='programpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='programpagebranding',
            name='program_title',
        ),
        migrations.AlterField(
            model_name='programpage',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
