# Generated by Django 1.11.22 on 2019-07-11 20:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190708_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='program_documents',
            field=wagtail.fields.StreamField((('file', wagtail.blocks.StructBlock((('display_text', wagtail.blocks.CharBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())), icon='doc-full')), ('link', wagtail.blocks.StructBlock((('display_text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())), icon='link'))), blank=True, verbose_name='Program Documents', use_json_field=True),
        ),
    ]
