# Generated by Django 1.11.22 on 2019-07-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_programpage_program_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='idp_slug',
            field=models.SlugField(default='', max_length=255, verbose_name='IDP Slug'),
        ),
    ]
