# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190716_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpage',
            name='idp_slug',
        ),
    ]
