# Generated by Django 1.11.22 on 2019-08-12 19:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_auto_20190703_1512'),
        ('wagtailcore', '0040_page_draft_title'),
        ('pages', '0013_remove_programpage_idp_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterprisePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('uuid', models.UUIDField(unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EnterprisePageBranding',
            fields=[
                ('branding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='branding.Branding')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='pages.EnterprisePage', unique=True)),
            ],
            bases=('branding.branding',),
        ),
    ]
