# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 14:33
from __future__ import unicode_literals

import designer.apps.branding.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_enterprisepage_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisepagebranding',
            name='banner_background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True, validators=[designer.apps.branding.utils.validate_hexadecimal_color]),
        ),
    ]
