# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 12:52
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Branding = apps.get_model('branding', 'Branding')
    ProgramPageBranding = apps.get_model('pages', 'ProgramPageBranding')
    for program_branding in ProgramPageBranding.objects.all():
        branding_id = program_branding.branding_ptr_id
        branding = Branding.objects.get(id=branding_id)
        program_branding.cover_image_new = branding.cover_image
        program_branding.texture_image_new = branding.texture_image
        program_branding.save()

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_add_page_specific_branding'),
        ('branding', '0002_auto_20190703_1512')
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
