# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('pages', '0016_enterprisepagebranding_banner_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpagebranding',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='programpagebranding',
            name='texture_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Texture Image'),
        ),
    ]
