# Generated by Django 1.11.23 on 2019-10-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_copy_existing_program_branding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programpagebranding',
            old_name='cover_image_new',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='programpagebranding',
            old_name='texture_image_new',
            new_name='texture_image',
        ),
    ]
