name: Upgrade Requirements

on:
  schedule:
     - cron: "15 3 14,29 * *"
  workflow_dispatch:
     inputs:
       branch:
         description: 'Target branch to create requirements PR against'
         required: true
         default: 'master'
jobs:
   call-upgrade-python-requirements-workflow:
    with:
       branch: ${{ github.event.inputs.branch }}
       team_reviewers: "masters-devs-cosmonauts"
       email_address: masters-requirements-update@edx.opsgenie.net
       send_success_notification: true
    uses: Coder-Aht007/.github/.github/workflows/upgrade-python-requirements.yml@master
